//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.QLTS.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.QLTS.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi gọi vào DL.
        /// </summary>
        public static string callDbError {
            get {
                return ResourceManager.GetString("callDbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua phải nhỏ hơn ngày sử dụng.
        /// </summary>
        public static string ConditionalDate {
            get {
                return ResourceManager.GetString("ConditionalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại tài sản không được để trống.
        /// </summary>
        public static string EmptyAssetCategoryCode {
            get {
                return ResourceManager.GetString("EmptyAssetCategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id loại tài sản không được để trống.
        /// </summary>
        public static string EmptyAssetCategoryId {
            get {
                return ResourceManager.GetString("EmptyAssetCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài sản không được để trống.
        /// </summary>
        public static string EmptyAssetName {
            get {
                return ResourceManager.GetString("EmptyAssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản không được để trống.
        /// </summary>
        public static string EmptyCode {
            get {
                return ResourceManager.GetString("EmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên giá không được bỏ trống.
        /// </summary>
        public static string EmptyCost {
            get {
                return ResourceManager.GetString("EmptyCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban không được để trống.
        /// </summary>
        public static string EmptyDepartmentCode {
            get {
                return ResourceManager.GetString("EmptyDepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id phòng ban không được để trống.
        /// </summary>
        public static string EmptyDepartmentId {
            get {
                return ResourceManager.GetString("EmptyDepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ lệ hao mòn không được bỏ trống.
        /// </summary>
        public static string EmptyDepreciationRate {
            get {
                return ResourceManager.GetString("EmptyDepreciationRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được bỏ trống.
        /// </summary>
        public static string emptyError {
            get {
                return ResourceManager.GetString("emptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số năm sử dụng không được bỏ trống.
        /// </summary>
        public static string EmptyLifeTime {
            get {
                return ResourceManager.GetString("EmptyLifeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sử dụng không được bỏ trống.
        /// </summary>
        public static string EmptyProductionYear {
            get {
                return ResourceManager.GetString("EmptyProductionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua không được bỏ trống.
        /// </summary>
        public static string EmptyPurchaseDate {
            get {
                return ResourceManager.GetString("EmptyPurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng không được bỏ trống.
        /// </summary>
        public static string EmptyQuantity {
            get {
                return ResourceManager.GetString("EmptyQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm bắt đầu theo dõi sản phẩm không được bỏ trống.
        /// </summary>
        public static string EmptyTrackedYear {
            get {
                return ResourceManager.GetString("EmptyTrackedYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản đã tồn tại.
        /// </summary>
        public static string ErrorDuplicate {
            get {
                return ResourceManager.GetString("ErrorDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải có số kí tự từ {1} đến {2}!.
        /// </summary>
        public static string errorLength {
            get {
                return ResourceManager.GetString("errorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi gọi vào DL.
        /// </summary>
        public static string ErrorToDL {
            get {
                return ResourceManager.GetString("ErrorToDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày không được vượt quá ngày hiện tại.
        /// </summary>
        public static string FormatDate {
            get {
                return ResourceManager.GetString("FormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ghi tăng.
        /// </summary>
        public static string increment_date {
            get {
                return ResourceManager.GetString("increment_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải chọn ít nhất 1 tài sản.
        /// </summary>
        public static string needAssetError {
            get {
                return ResourceManager.GetString("needAssetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA để được trợ giúp.
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài sản update thất bại.
        /// </summary>
        public static string updateAssetFall {
            get {
                return ResourceManager.GetString("updateAssetFall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chứng từ.
        /// </summary>
        public static string voucher_code {
            get {
                return ResourceManager.GetString("voucher_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày chứng từ.
        /// </summary>
        public static string voucher_date {
            get {
                return ResourceManager.GetString("voucher_date", resourceCulture);
            }
        }
    }
}
